#!/bin/bash
set -euo pipefail

# Build script: merges SKILL.md + EEA-OVERRIDES.md into dist/
# Usage: ./scripts/build.sh [skill-name]
# If no skill-name provided, builds all skills

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(dirname "$SCRIPT_DIR")"
SKILLS_DIR="$REPO_ROOT/skills"
DIST_DIR="$REPO_ROOT/dist/skills"

build_skill() {
    local skill_name="$1"
    local skill_dir="$SKILLS_DIR/$skill_name"
    local dist_skill_dir="$DIST_DIR/$skill_name"

    if [ ! -d "$skill_dir" ]; then
        echo "ERROR: Skill '$skill_name' not found in $SKILLS_DIR"
        exit 1
    fi

    if [ ! -f "$skill_dir/SKILL.md" ]; then
        echo "ERROR: SKILL.md missing for '$skill_name'"
        exit 1
    fi

    mkdir -p "$dist_skill_dir"

    # Create merged SKILL.md
    {
        echo "<!-- Merged Build: upstream SKILL.md + EEA-OVERRIDES.md -->"
        echo "<!-- Auto-generated by scripts/build.sh - DO NOT EDIT DIRECTLY -->"
        echo "<!-- Source: https://github.com/eea/eea.agent.skills -->"
        echo ""
        cat "$skill_dir/SKILL.md"

        if [ -f "$skill_dir/EEA-OVERRIDES.md" ]; then
            echo ""
            echo "---"
            echo ""
            echo "<!-- BEGIN EEA-OVERRIDES -->"
            cat "$skill_dir/EEA-OVERRIDES.md"
            echo ""
            echo "<!-- END EEA-OVERRIDES -->"
        fi
    } > "$dist_skill_dir/SKILL.md"

    # Copy references if they exist
    if [ -d "$skill_dir/references" ]; then
        cp -r "$skill_dir/references" "$dist_skill_dir/"
    fi

    echo "✓ Built: $skill_name -> $dist_skill_dir/SKILL.md"
}

# Main
if [ $# -eq 0 ]; then
    # Build all skills (directories with a SKILL.md file)
    for skill_dir in "$SKILLS_DIR"/*/; do
        if [ -d "$skill_dir" ] && [ -f "$skill_dir/SKILL.md" ]; then
            skill_name="$(basename "$skill_dir")"
            build_skill "$skill_name"
        fi
    done
else
    # Build specific skill
    build_skill "$1"
fi

echo ""
echo "Build complete. Merged skills available in: $DIST_DIR"
